# Generated by Django 3.0.10 on 2021-10-25 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Model',
            fields=[
                ('model', models.CharField(blank=True, db_column='Model', max_length=255, null=True)),
                ('tooltype', models.CharField(blank=True, db_column='Tooltype', max_length=255, null=True)),
                ('excel', models.CharField(blank=True, db_column='Excel', max_length=255, null=True)),
                ('img', models.CharField(blank=True, max_length=255, null=True)),
                ('point', models.CharField(blank=True, db_column='Point', max_length=255, null=True)),
                ('toolname', models.CharField(blank=True, db_column='Toolname', max_length=255, null=True)),
                ('shift', models.CharField(blank=True, max_length=255, null=True)),
                ('machine_line', models.CharField(blank=True, db_column='Machine_Line', max_length=250, null=True)),
                ('machine_no', models.CharField(blank=True, db_column='Machine_No', max_length=250, null=True)),
                ('machine_process', models.CharField(blank=True, db_column='Machine_Process', max_length=250, null=True)),
                ('processname', models.CharField(blank=True, db_column='Processname', max_length=250, null=True)),
                ('partname', models.CharField(blank=True, db_column='Partname', max_length=250, null=True)),
                ('wid', models.AutoField(primary_key=True, serialize=False)),
                ('point_no', models.FloatField(blank=True, db_column='Point_No', null=True)),
                ('sheet', models.TextField(blank=True, db_column='Sheet', null=True)),
                ('min', models.FloatField(blank=True, db_column='Min', null=True)),
                ('max', models.FloatField(blank=True, db_column='Max', null=True)),
                ('wi', models.IntegerField(blank=True, null=True)),
                ('pattern_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Model',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Pattern',
            fields=[
                ('pattern_id', models.AutoField(primary_key=True, serialize=False)),
                ('direction', models.CharField(max_length=255)),
                ('cstart', models.IntegerField()),
                ('rstart', models.IntegerField()),
                ('interval', models.IntegerField()),
            ],
            options={
                'db_table': 'Pattern',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('tid', models.AutoField(primary_key=True, serialize=False)),
                ('toolname', models.CharField(blank=True, db_column='Toolname', max_length=50, null=True)),
                ('ttid', models.IntegerField(blank=True, null=True)),
                ('tooltype', models.CharField(blank=True, db_column='Tooltype', max_length=50, null=True)),
            ],
            options={
                'db_table': 'Tool',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Toollist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tid', models.CharField(blank=True, max_length=255, null=True)),
                ('codename', models.CharField(blank=True, db_column='CodeName', max_length=255, null=True)),
            ],
            options={
                'db_table': 'Tool_',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Tooltype',
            fields=[
                ('ttid', models.IntegerField(primary_key=True, serialize=False)),
                ('type', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'Tooltype',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('man', models.CharField(blank=True, db_column='Man', max_length=255, null=True)),
                ('timein', models.CharField(blank=True, db_column='Timein', max_length=255, null=True)),
                ('timeout', models.CharField(blank=True, db_column='Timeout', max_length=255, null=True)),
                ('duration', models.CharField(blank=True, db_column='Duration', max_length=255, null=True)),
                ('date', models.DateField(auto_now_add=True, db_column='Date', max_length=255, null=True)),
                ('wid', models.IntegerField(blank=True, null=True)),
                ('result', models.CharField(blank=True, db_column='Result', max_length=255, null=True)),
                ('number', models.CharField(blank=True, db_column='Number', max_length=255, null=True)),
                ('shift', models.CharField(blank=True, max_length=255, null=True)),
                ('partno', models.CharField(blank=True, db_column='PartNo', max_length=255, null=True)),
                ('point', models.CharField(blank=True, db_column='Point', max_length=255, null=True)),
                ('model', models.CharField(blank=True, db_column='Model', max_length=255, null=True)),
                ('machineprocess', models.CharField(blank=True, db_column='MachineProcess', max_length=255, null=True)),
                ('processname', models.CharField(blank=True, db_column='Processname', max_length=255, null=True)),
                ('machine_line', models.CharField(blank=True, db_column='Machine_Line', max_length=255, null=True)),
                ('machine_no', models.CharField(blank=True, db_column='Machine_No', max_length=255, null=True)),
                ('point_no', models.CharField(blank=True, db_column='Point_No', max_length=255, null=True)),
                ('toolname', models.CharField(blank=True, db_column='Toolname', max_length=255, null=True)),
                ('result_gonogo', models.CharField(blank=True, db_column='Result_gonogo', max_length=255, null=True)),
                ('partname', models.TextField(blank=True, db_column='Partname', null=True)),
                ('rid', models.AutoField(primary_key=True, serialize=False)),
                ('max', models.FloatField(blank=True, db_column='Max', null=True)),
                ('min', models.FloatField(blank=True, db_column='Min', null=True)),
                ('wi', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Work',
                'managed': True,
            },
        ),
    ]
