# Generated by Django 3.0.10 on 2021-11-08 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20211027_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='pattern',
            name='name_shift',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='pattern',
            name='num_shift',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pattern',
            name='cstart',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pattern',
            name='interval',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pattern',
            name='rstart',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
