# Generated by Django 3.0.10 on 2021-11-09 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20211108_1131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='model',
            name='pattern_id',
        ),
        migrations.AddField(
            model_name='model',
            name='pattern',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
