# Generated by Django 3.0.10 on 2021-11-11 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20211109_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='pattern',
            name='shift_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
